language: python
python:
  - 2.6
  - 2.7
install:
  - pip install 'requests>=1.0' --use-mirrors
  - python setup.py install
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install --use-mirrors unittest2; fi
script: nosetests tests
notifications:
  email:
    recipients:
      - marselester@ya.ru
    on_success: change
    on_failure: change
