language: python
python:
  - 2.7
install:
  - pip install 'requests>=1.0' --use-mirrors
  - python setup.py install
script: nosetests tests
notifications:
  email:
    recipients:
      - marselester@ya.ru
    on_success: change
    on_failure: change
